[2025-04-27 21:04:35 +1000] [32252] [INFO] Starting gunicorn 21.2.0
[2025-04-27 21:04:35 +1000] [32252] [INFO] Listening at: http://0.0.0.0:8000 (32252)
[2025-04-27 21:04:35 +1000] [32252] [INFO] Using worker: sync
[2025-04-27 21:04:35 +1000] [32255] [INFO] Booting worker with pid: 32255
[2025-04-27 21:04:38 +1000] [32255] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/jumer/.local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/jumer/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/jumer/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/jumer/.local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/jumer/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/jumer/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/jumer/.local/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jumer/SENG3011-Foxtrot/src/app.py", line 18, in <module>
    from prices import get_indicators, get_prices
  File "/home/jumer/SENG3011-Foxtrot/src/prices.py", line 23, in <module>
    from alpaca.data import CryptoHistoricalDataClient
ModuleNotFoundError: No module named 'alpaca.data'; 'alpaca' is not a package
[2025-04-27 21:04:38 +1000] [32255] [INFO] Worker exiting (pid: 32255)
[2025-04-27 21:04:39 +1000] [32252] [ERROR] Worker (pid:32255) exited with code 3
[2025-04-27 21:04:39 +1000] [32252] [ERROR] Shutting down: Master
[2025-04-27 21:04:39 +1000] [32252] [ERROR] Reason: Worker failed to boot.
[2025-04-27 22:01:56 +1000] [22377] [INFO] Starting gunicorn 21.2.0
[2025-04-27 22:01:56 +1000] [22377] [INFO] Listening at: http://0.0.0.0:8000 (22377)
[2025-04-27 22:01:56 +1000] [22377] [INFO] Using worker: sync
[2025-04-27 22:01:56 +1000] [22379] [INFO] Booting worker with pid: 22379
[2025-04-27 22:01:57 +1000] [22379] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/jumer/.local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/jumer/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/jumer/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/jumer/.local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/jumer/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/jumer/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/jumer/.local/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jumer/SENG3011-Foxtrot/src/app.py", line 18, in <module>
    from prices import get_indicators, get_prices
  File "/home/jumer/SENG3011-Foxtrot/src/prices.py", line 23, in <module>
    from alpaca.data import CryptoHistoricalDataClient
ModuleNotFoundError: No module named 'alpaca.data'; 'alpaca' is not a package
[2025-04-27 22:01:57 +1000] [22379] [INFO] Worker exiting (pid: 22379)
[2025-04-27 22:01:57 +1000] [22377] [ERROR] Worker (pid:22379) exited with code 3
[2025-04-27 22:01:57 +1000] [22377] [ERROR] Shutting down: Master
[2025-04-27 22:01:57 +1000] [22377] [ERROR] Reason: Worker failed to boot.
[2025-04-27 22:02:37 +1000] [22419] [INFO] Starting gunicorn 21.2.0
[2025-04-27 22:02:37 +1000] [22419] [INFO] Listening at: http://0.0.0.0:8000 (22419)
[2025-04-27 22:02:37 +1000] [22419] [INFO] Using worker: sync
[2025-04-27 22:02:37 +1000] [22420] [INFO] Booting worker with pid: 22420
[2025-04-27 22:02:38 +1000] [22420] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/jumer/.local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/jumer/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/jumer/.local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/jumer/.local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/jumer/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/jumer/.local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/jumer/.local/lib/python3.10/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jumer/SENG3011-Foxtrot/src/app.py", line 18, in <module>
    from prices import get_indicators, get_prices
  File "/home/jumer/SENG3011-Foxtrot/src/prices.py", line 23, in <module>
    from alpaca.data import CryptoHistoricalDataClient
ModuleNotFoundError: No module named 'alpaca.data'; 'alpaca' is not a package
[2025-04-27 22:02:38 +1000] [22420] [INFO] Worker exiting (pid: 22420)
[2025-04-27 22:02:38 +1000] [22419] [ERROR] Worker (pid:22420) exited with code 3
[2025-04-27 22:02:38 +1000] [22419] [ERROR] Shutting down: Master
[2025-04-27 22:02:38 +1000] [22419] [ERROR] Reason: Worker failed to boot.
